-- =============================================
-- 1. СОЗДАНИЕ СХЕМЫ И ПРИВИЛЕГИЙ
-- =============================================

CREATE SCHEMA IF NOT EXISTS app AUTHORIZATION app;

GRANT USAGE, CREATE ON SCHEMA app TO app;

ALTER DEFAULT PRIVILEGES IN SCHEMA app
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app;

ALTER DEFAULT PRIVILEGES IN SCHEMA app
GRANT USAGE, SELECT ON SEQUENCES TO app;

SET SEARCH_PATH TO app;

-- =============================================
-- 2. СОЗДАНИЕ ТАБЛИЦ
-- =============================================

CREATE TABLE app.partner_types
(
    id      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    varchar(100) NOT NULL UNIQUE
);

CREATE TABLE app.partners
(
    id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_id             integer NOT NULL,
    company_name        varchar(255) NOT NULL,
    address             varchar(500) NOT NULL,
    inn                 varchar(12) UNIQUE,
    director_fullname   varchar(255) NOT NULL,
    phone               varchar(30) NOT NULL,
    email               varchar(255) NOT NULL UNIQUE,
    rating              integer NOT NULL,
    logo_path           varchar(500),
    sales_places        text,
    created_at          timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_partners_type
        FOREIGN KEY (type_id)
        REFERENCES app.partner_types(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT ck_partners_rating_non_negative
        CHECK (rating >= 0),

    CONSTRAINT ck_partners_inn_length
        CHECK (inn IS NULL OR char_length(inn) IN (10, 12))
);

CREATE TABLE app.products
(
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article         varchar(50) NOT NULL UNIQUE,
    product_type    varchar(100),
    name            varchar(255) NOT NULL,
    price           numeric(12,2) NOT NULL,
    is_active       boolean NOT NULL DEFAULT true,

    CONSTRAINT ck_products_price_non_negative
        CHECK (price >= 0)
);

CREATE TABLE app.partner_product_sales
(
    id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    partner_id          integer NOT NULL,
    product_id          integer NOT NULL,
    quantity            integer NOT NULL,
    sale_date           date NOT NULL,
    base_price          numeric(12,2) NOT NULL,
    discount_percent    integer NOT NULL,
    unit_price          numeric(12,2) NOT NULL,
    total_amount        numeric(14,2) GENERATED ALWAYS AS (quantity * unit_price) STORED,
    comment             text,

    CONSTRAINT fk_sales_partner
        FOREIGN KEY (partner_id)
        REFERENCES app.partners(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_sales_product
        FOREIGN KEY (product_id)
        REFERENCES app.products(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT ck_sales_quantity_positive
        CHECK (quantity > 0),

    CONSTRAINT ck_sales_base_price_non_negative
        CHECK (base_price >= 0),

    CONSTRAINT ck_sales_discount_percent_range
        CHECK (discount_percent >= 0 AND discount_percent <= 100),

    CONSTRAINT ck_sales_unit_price_non_negative
        CHECK (unit_price >= 0)
);


-- =============================================
-- 3. ИНДЕКСЫ
-- =============================================

CREATE INDEX idx_partners_type_id
    ON app.partners(type_id);

CREATE INDEX idx_partners_company_name
    ON app.partners(company_name);

CREATE INDEX idx_sales_partner_id
    ON app.partner_product_sales(partner_id);

CREATE INDEX idx_sales_product_id
    ON app.partner_product_sales(product_id);

CREATE INDEX idx_sales_sale_date
    ON app.partner_product_sales(sale_date);

CREATE INDEX idx_sales_partner_date
    ON app.partner_product_sales(partner_id, sale_date);


-- =============================================
-- 4. ПРИВИЛЕГИИ НА УЖЕ СОЗДАННЫЕ ОБЪЕКТЫ
-- =============================================

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA app
TO app;

GRANT USAGE, SELECT
ON ALL SEQUENCES IN SCHEMA app
TO app;